name: Infrastructure checks

on:
  pull_request:

permissions:
  contents: read
  checks: write

jobs:
  infrastructure:
    runs-on: ubuntu-latest
    steps:
      - name: Test 1
        run: |
          sleep 12
          echo "Success"
      - name: Test 2
        run: |
          sleep 60
          echo "Success"
