name: Pull request checks

on:
  issue_comment:
    types: [created]

permissions:
  contents: read
  checks: write

jobs:
  pipeline:
    if: startsWith(github.event.comment.body, '/pipeline')
    runs-on: ubuntu-latest
    steps:
      - name: SetUp
        run: |
          git clone --depth 1 https://github.com/rhinstaller/permian.git
          pushd permian
          ./build_container
          popd
      - name: Run pipeline
        working-directory: ./permian
        run: |
          echo ${{ github.event.issue.number }}
          echo "- type: github-pr" > tests/test_library/demo/github_rep.yaml
          ./in_container ./pipeline \
            -o reportSenders.additional_reporting=library://github_rep.yaml \
            -o github.pull-request=${{ github.event.issue.number }} \
            -o github.repository=${{ github.repository }} \
            -o github.token=${{ secrets.GITHUB_TOKEN }} \
            demo
